/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz.satisfacibilidad;

import help.Help;
import java.awt.Robot;
import javax.swing.JOptionPane;
import logica.satisfacibilidad.CustomFont;
import logica.satisfacibilidad.LogicaSatisfacibilidad;

/**
 *
 * @author PC
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    Robot robot;
    LogicaSatisfacibilidad logicaSatisfacibilidad;
    GenerarTabla generar;
    int posicionRetornaBoton = 0;
    CustomFont cf = new CustomFont();
    boolean presionoVerTabla = false;

    public Principal() {
        initComponents();
        txtInsertarFormula.setFont(cf.MyFont(0, 26));
        txtFormulasProposicionales.setFont(cf.MyFont(0, 26));
        this.setSize(1117, 555);
        this.setLocationRelativeTo(this);
        logicaSatisfacibilidad = new LogicaSatisfacibilidad();
        txtInsertarFormula.requestFocus();
        this.setResizable(false);
        //txtInsertarFormula.setEditable(false);
        txtFormulasProposicionales.setEditable(false);
        lblPosicionCursor.setVisible(false);
        lblPosicion.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcMousePanel1 = new jcMousePanel.jcMousePanel();
        btnAgregarFormula = new javax.swing.JButton();
        btnGenerarTabla = new javax.swing.JButton();
        btnVerificarSatisfa = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnAgregarDobleImplicacion = new javax.swing.JButton();
        btnAgregarImplicacion = new javax.swing.JButton();
        btnAgregarO = new javax.swing.JButton();
        btnAgregarY = new javax.swing.JButton();
        btnAgregarNegacion = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnAgregarP = new javax.swing.JButton();
        btnAgregarQ = new javax.swing.JButton();
        btnAgregarR = new javax.swing.JButton();
        btnAgregarS = new javax.swing.JButton();
        btnAgregarT = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInsertarFormula = new javax.swing.JTextArea();
        btnBorrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtFormulasProposicionales = new javax.swing.JTextArea();
        btnPosicionarCursor = new javax.swing.JButton();
        lblPosicionCursor = new javax.swing.JLabel();
        lblPosicion = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jcMousePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/recursos.imagenes/fondoprincipal.png"))); // NOI18N
        jcMousePanel1.setIconLogo(new javax.swing.ImageIcon(getClass().getResource("/recursos/recursos.imagenes/fondoprincipal.png"))); // NOI18N
        jcMousePanel1.setMinimumSize(new java.awt.Dimension(1108, 525));

        btnAgregarFormula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/recursos.imagenes/+.png"))); // NOI18N
        btnAgregarFormula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarFormulaActionPerformed(evt);
            }
        });

        btnGenerarTabla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/recursos.imagenes/generar tabla.png"))); // NOI18N
        btnGenerarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarTablaActionPerformed(evt);
            }
        });

        btnVerificarSatisfa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/recursos.imagenes/verificar.png"))); // NOI18N
        btnVerificarSatisfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarSatisfaActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnAgregarDobleImplicacion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAgregarDobleImplicacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/recursos.imagenes/boton 5.png"))); // NOI18N
        btnAgregarDobleImplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarDobleImplicacionActionPerformed(evt);
            }
        });

        btnAgregarImplicacion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAgregarImplicacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/recursos.imagenes/boton 4.png"))); // NOI18N
        btnAgregarImplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarImplicacionActionPerformed(evt);
            }
        });

        btnAgregarO.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAgregarO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/recursos.imagenes/boton 3.png"))); // NOI18N
        btnAgregarO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarOActionPerformed(evt);
            }
        });

        btnAgregarY.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAgregarY.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/recursos.imagenes/boton 2.png"))); // NOI18N
        btnAgregarY.setToolTipText("");
        btnAgregarY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarYActionPerformed(evt);
            }
        });

        btnAgregarNegacion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAgregarNegacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/recursos.imagenes/boton 1.png"))); // NOI18N
        btnAgregarNegacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarNegacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregarDobleImplicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAgregarO, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnAgregarNegacion, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregarY, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarImplicacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAgregarNegacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregarY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAgregarO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregarImplicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregarDobleImplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Letras proposicionales"));

        btnAgregarP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAgregarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/recursos.imagenes/p.png"))); // NOI18N
        btnAgregarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPActionPerformed(evt);
            }
        });

        btnAgregarQ.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAgregarQ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/recursos.imagenes/q.png"))); // NOI18N
        btnAgregarQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarQActionPerformed(evt);
            }
        });

        btnAgregarR.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAgregarR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/recursos.imagenes/r.png"))); // NOI18N
        btnAgregarR.setToolTipText("");
        btnAgregarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarRActionPerformed(evt);
            }
        });

        btnAgregarS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAgregarS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/recursos.imagenes/s.png"))); // NOI18N
        btnAgregarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarSActionPerformed(evt);
            }
        });

        btnAgregarT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAgregarT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/recursos.imagenes/t.png"))); // NOI18N
        btnAgregarT.setToolTipText("");
        btnAgregarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnAgregarP, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btnAgregarQ, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregarR, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAgregarS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregarT, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAgregarS)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnAgregarT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregarR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregarQ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAgregarP)))
                .addContainerGap())
        );

        txtInsertarFormula.setEditable(false);
        txtInsertarFormula.setColumns(20);
        txtInsertarFormula.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtInsertarFormula.setForeground(new java.awt.Color(30, 42, 63));
        txtInsertarFormula.setRows(5);
        txtInsertarFormula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtInsertarFormulaMouseClicked(evt);
            }
        });
        txtInsertarFormula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInsertarFormulaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txtInsertarFormula);

        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/recursos.imagenes/-.png"))); // NOI18N
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtFormulasProposicionales.setColumns(20);
        txtFormulasProposicionales.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtFormulasProposicionales.setForeground(new java.awt.Color(30, 42, 63));
        txtFormulasProposicionales.setRows(5);
        jScrollPane2.setViewportView(txtFormulasProposicionales);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnPosicionarCursor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/recursos.imagenes/cursor.png"))); // NOI18N
        btnPosicionarCursor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPosicionarCursorActionPerformed(evt);
            }
        });

        lblPosicionCursor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPosicionCursor.setText("Posicion Cursor: ");

        lblPosicion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPosicion.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jcMousePanel1Layout = new javax.swing.GroupLayout(jcMousePanel1);
        jcMousePanel1.setLayout(jcMousePanel1Layout);
        jcMousePanel1Layout.setHorizontalGroup(
            jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jcMousePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jcMousePanel1Layout.createSequentialGroup()
                        .addComponent(lblPosicionCursor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(269, 269, 269))
                    .addGroup(jcMousePanel1Layout.createSequentialGroup()
                        .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jcMousePanel1Layout.createSequentialGroup()
                                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jcMousePanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jcMousePanel1Layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(btnGenerarTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnVerificarSatisfa, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnPosicionarCursor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAgregarFormula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36)))
                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        jcMousePanel1Layout.setVerticalGroup(
            jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jcMousePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPosicionCursor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregarFormula)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jcMousePanel1Layout.createSequentialGroup()
                        .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPosicionarCursor, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jcMousePanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGenerarTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVerificarSatisfa, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jcMousePanel1Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jcMousePanel1);
        jcMousePanel1.setBounds(0, 0, 1108, 525);

        jMenu1.setText("Participantes");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Integrantes");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jCheckBoxMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("Ayuda");
        jCheckBoxMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jCheckBoxMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarTablaActionPerformed

        logicaSatisfacibilidad.ObtenerLetras();
        GenerarTabla generarTabla = new GenerarTabla(logicaSatisfacibilidad);
        if (logicaSatisfacibilidad.isVerInterfazTabla()) {

            generarTabla.setVisible(true);
            presionoVerTabla = true;
        }
    }//GEN-LAST:event_btnGenerarTablaActionPerformed

    private void btnAgregarNegacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarNegacionActionPerformed
        agregarOperadoresLogicos("~()");
    }//GEN-LAST:event_btnAgregarNegacionActionPerformed

    private void btnAgregarYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarYActionPerformed
        agregarOperadoresLogicos("()^()");
    }//GEN-LAST:event_btnAgregarYActionPerformed

    private void btnAgregarOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarOActionPerformed
        agregarOperadoresLogicos("()v()");
    }//GEN-LAST:event_btnAgregarOActionPerformed

    private void btnAgregarImplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarImplicacionActionPerformed
        agregarOperadoresLogicos("()->()");
    }//GEN-LAST:event_btnAgregarImplicacionActionPerformed

    private void btnAgregarDobleImplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarDobleImplicacionActionPerformed
        agregarOperadoresLogicos("()<->()");
    }//GEN-LAST:event_btnAgregarDobleImplicacionActionPerformed

    private void btnAgregarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPActionPerformed

        txtInsertarFormula.insert("P", logicaSatisfacibilidad.ubicarCursorConLetra(txtInsertarFormula));
        logicaSatisfacibilidad.getLetrasAgregadas().add("P");

    }//GEN-LAST:event_btnAgregarPActionPerformed

    private void btnAgregarQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarQActionPerformed

        txtInsertarFormula.insert("Q", logicaSatisfacibilidad.ubicarCursorConLetra(txtInsertarFormula));
        logicaSatisfacibilidad.getLetrasAgregadas().add("Q");

    }//GEN-LAST:event_btnAgregarQActionPerformed

    private void btnAgregarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarRActionPerformed

        txtInsertarFormula.insert("R", logicaSatisfacibilidad.ubicarCursorConLetra(txtInsertarFormula));
        logicaSatisfacibilidad.getLetrasAgregadas().add("R");

    }//GEN-LAST:event_btnAgregarRActionPerformed

    private void btnAgregarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarSActionPerformed

        txtInsertarFormula.insert("S", logicaSatisfacibilidad.ubicarCursorConLetra(txtInsertarFormula));
        logicaSatisfacibilidad.getLetrasAgregadas().add("S");

    }//GEN-LAST:event_btnAgregarSActionPerformed

    private void txtInsertarFormulaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInsertarFormulaKeyPressed

    }//GEN-LAST:event_txtInsertarFormulaKeyPressed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        if (!logicaSatisfacibilidad.getLetrasAgregadas().empty()) {
            String borrar = logicaSatisfacibilidad.getLetrasAgregadas().pop();
            txtInsertarFormula.setText(txtInsertarFormula.getText().replace(borrar, ""));
            if (txtInsertarFormula.getText().contains(")")) {
                txtInsertarFormula.setCaretPosition(txtInsertarFormula.getText().indexOf(")"));
            }
        } else {
            lblPosicionCursor.setVisible(false);
            lblPosicion.setVisible(false);
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnAgregarFormulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarFormulaActionPerformed
        if (txtInsertarFormula.getText().length() >= 4) {
            logicaSatisfacibilidad.getAgregarFormula().add(txtInsertarFormula.getText());
            txtFormulasProposicionales.append(txtInsertarFormula.getText());
            txtFormulasProposicionales.append("\n");
            txtInsertarFormula.setText("");

        }
    }//GEN-LAST:event_btnAgregarFormulaActionPerformed

    private void btnVerificarSatisfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarSatisfaActionPerformed
        logicaSatisfacibilidad.ObtenerLetras();
        logicaSatisfacibilidad.generarSatisfacibilidad();
        if (logicaSatisfacibilidad.isVerMensajeSatisfacible()) {
            JOptionPane.showMessageDialog(this, logicaSatisfacibilidad.getSatisfacible());
        }

    }//GEN-LAST:event_btnVerificarSatisfaActionPerformed

    private void btnAgregarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTActionPerformed
        txtInsertarFormula.insert("T", logicaSatisfacibilidad.ubicarCursorConLetra(txtInsertarFormula));
        logicaSatisfacibilidad.getLetrasAgregadas().add("T");
    }//GEN-LAST:event_btnAgregarTActionPerformed

    private void btnPosicionarCursorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPosicionarCursorActionPerformed
        this.posicionRetornaBoton = (int) logicaSatisfacibilidad.ubicarCursorConBoton(txtInsertarFormula);
        lblPosicionCursor.setVisible(true);
        lblPosicion.setVisible(true);
        lblPosicion.setText(String.valueOf(this.logicaSatisfacibilidad.getPosicionesBoton()));

    }//GEN-LAST:event_btnPosicionarCursorActionPerformed

    private void txtInsertarFormulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtInsertarFormulaMouseClicked

    }//GEN-LAST:event_txtInsertarFormulaMouseClicked

    private void jCheckBoxMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem2ActionPerformed
        // TODO add your handling code here:
        Help help = new Help();
        help.setVisible(true);
    }//GEN-LAST:event_jCheckBoxMenuItem2ActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        // TODO add your handling code here:
        Integrantes integrantes = new Integrantes();
        integrantes.setVisible(true);
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarDobleImplicacion;
    private javax.swing.JButton btnAgregarFormula;
    private javax.swing.JButton btnAgregarImplicacion;
    private javax.swing.JButton btnAgregarNegacion;
    private javax.swing.JButton btnAgregarO;
    private javax.swing.JButton btnAgregarP;
    private javax.swing.JButton btnAgregarQ;
    private javax.swing.JButton btnAgregarR;
    private javax.swing.JButton btnAgregarS;
    private javax.swing.JButton btnAgregarT;
    private javax.swing.JButton btnAgregarY;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnGenerarTabla;
    private javax.swing.JButton btnPosicionarCursor;
    private javax.swing.JButton btnVerificarSatisfa;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private jcMousePanel.jcMousePanel jcMousePanel1;
    private javax.swing.JLabel lblPosicion;
    private javax.swing.JLabel lblPosicionCursor;
    private javax.swing.JTextArea txtFormulasProposicionales;
    private javax.swing.JTextArea txtInsertarFormula;
    // End of variables declaration//GEN-END:variables

    public void agregarOperadoresLogicos(String formula) {
        if (this.posicionRetornaBoton != 0) {
            if (txtInsertarFormula.getText().length() == 0) {
                this.posicionRetornaBoton = 0;
            }
            txtInsertarFormula.insert(formula, this.posicionRetornaBoton);
        } else {
            txtInsertarFormula.insert(formula, logicaSatisfacibilidad.ubicarCursor(txtInsertarFormula));
        }
        logicaSatisfacibilidad.getLetrasAgregadas().add(formula);
        lblPosicionCursor.setVisible(false);
        lblPosicion.setVisible(false);
        this.posicionRetornaBoton = 0;
    }

}
